services:
  mysql:
    image: mysql:8.0
    container_name: edx_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: edxapp
      MYSQL_USER: edxapp_user
      MYSQL_PASSWORD: edxapp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=STRICT_TRANS_TABLES --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: edx_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: edxapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  memcached:
    image: memcached:1.6-alpine
    container_name: edx_memcached
    ports:
      - "11211:11211"
    command: memcached -m 256
    restart: unless-stopped

volumes:
  mysql_data:
  mongodb_data:
